[package]
name = "colorschemes"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
